---
# tasks file for phpbrew
- name: make sure required packages are installed
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - php7.0
    - php7.0-curl
    - php7.0-json
    - php7.0-cgi
    - php7.0-fpm
    - autoconf
    - automake
    - libxml2-dev
    - libcurl4-openssl-dev
    - libssl-dev 
    - openssl 
    - gettext
    - libicu-dev
    - libmcrypt-dev
    - libmcrypt4 
    - libbz2-dev 
    - libreadline-dev 
    - build-essential 
    - libmhash-dev 
    - libmhash2 
    - libxslt1-dev

